<a href="https://colab.research.google.com/github/VariableSoporte/perceptron_diagnostico_medico/blob/main/perceptron_diagnostico_medico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ejercicio**
Realiza un perceptrón que pueda decidir si los pacientes estan en riesgo basandose en la edad, presión, colesterol y el indice de masa corporal.

| ID | Edad | Presión | Colest. | IMC | Riesgo | ID | Edad | Presión | Colest. | IMC | Riesgo |
|----|------|---------|---------|-----|--------|----|------|---------|---------|-----|--------|
| 1  | 72   | 160     | 280     | 32  | 1      | 21 | 48   | 132     | 215     | 27  | 0      |
| 2  | 24   | 110     | 170     | 22  | 0      | 22 | 62   | 148     | 245     | 31  | 1      |
| 3  | 65   | 145     | 240     | 29  | 1      | 23 | 29   | 118     | 185     | 24  | 0      |
| 4  | 30   | 120     | 190     | 24  | 0      | 24 | 75   | 165     | 290     | 34  | 1      |
| 5  | 58   | 155     | 260     | 35  | 1      | 25 | 38   | 128     | 200     | 25  | 0      |
| 6  | 45   | 130     | 210     | 26  | 0      | 26 | 54   | 142     | 235     | 29  | 1      |
| 7  | 80   | 170     | 300     | 30  | 1      | 27 | 21   | 112     | 165     | 22  | 0      |
| 8  | 19   | 115     | 160     | 21  | 0      | 28 | 68   | 158     | 270     | 33  | 1      |
| 9  | 50   | 140     | 220     | 28  | 1      | 29 | 42   | 130     | 205     | 26  | 0      |
| 10 | 35   | 125     | 185     | 23  | 0      | 30 | 59   | 152     | 255     | 31  | 1      |
| 11 | 61   | 150     | 250     | 30  | 1      | 31 | 31   | 122     | 195     | 24  | 0      |
| 12 | 27   | 115     | 175     | 23  | 0      | 32 | 66   | 146     | 242     | 30  | 1      |
| 13 | 55   | 142     | 230     | 33  | 1      | 33 | 46   | 135     | 220     | 27  | 0      |
| 14 | 40   | 128     | 200     | 25  | 0      | 34 | 71   | 155     | 265     | 32  | 1      |
| 15 | 69   | 162     | 275     | 31  | 1      | 35 | 25   | 116     | 180     | 22  | 0      |
| 16 | 22   | 112     | 168     | 21  | 0      | 36 | 57   | 145     | 250     | 29  | 1      |
| 17 | 47   | 135     | 215     | 27  | 0      | 37 | 34   | 124     | 192     | 25  | 0      |
| 18 | 78   | 168     | 295     | 35  | 1      | 38 | 64   | 150     | 248     | 31  | 1      |
| 19 | 33   | 122     | 188     | 24  | 0      | 39 | 28   | 119     | 178     | 23  | 0      |
| 20 | 52   | 145     | 240     | 28  | 1      | 40 | 73   | 162     | 285     | 33  | 1      |

## **Normalización**
Existen varias técnicas de normalización sin embargo una de las mas comunes para aplicar en perceptrones es la **Normalización Min-Max**. Esta técnica transforma cualquier valor para que quede en el rango de 0 a 1.

Su formula es:


$$x_{norm} = \frac{x - x_{min}}{x_{max} - x_{min}}$$


In [32]:
import numpy as np

#Matriz de datos: [Edad, Presión, Colesterol, IMC]
datos_raw = np.array([
    [72, 160, 280, 32], [24, 110, 170, 22], [65, 145, 240, 29], [30, 120, 190, 24],
    [58, 155, 260, 35], [45, 130, 210, 26], [80, 170, 300, 30], [19, 115, 160, 21],
    [50, 140, 220, 28], [35, 125, 185, 23], [61, 150, 250, 30], [27, 115, 175, 23],
    [55, 142, 230, 33], [40, 128, 200, 25], [69, 162, 275, 31], [22, 112, 168, 21],
    [47, 135, 215, 27], [78, 168, 295, 35], [33, 122, 188, 24], [52, 145, 240, 28],
    [48, 132, 215, 27], [62, 148, 245, 31], [29, 118, 185, 24], [75, 165, 290, 34],
    [38, 128, 200, 25], [54, 142, 235, 29], [21, 112, 165, 22], [68, 158, 270, 33],
    [42, 130, 205, 26], [59, 152, 255, 31], [31, 122, 195, 24], [66, 146, 242, 30],
    [46, 135, 220, 27], [71, 155, 265, 32], [25, 116, 180, 22], [57, 145, 250, 29],
    [34, 124, 192, 25], [64, 150, 248, 31], [28, 119, 178, 23], [73, 162, 285, 33]
])

#Etiquetas con valores reales
etiquetas = np.array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
                      0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

#Realizar normalización
minimos = datos_raw.min(axis=0) #axis=0 -> esto toma los minimos o maximos por columna
maximos = datos_raw.max(axis=0) #Si utilizamos axis=1 -> tomaria los minimos o maximos por fila
print(f"Minimos: {minimos}, Maximos: {maximos}\n")

datos_normalizados = (datos_raw - minimos)/(maximos-minimos)

print("Primeros 3 registros normalizados: ")
print(datos_normalizados[:3])

Minimos: [ 19 110 160  21], Maximos: [ 80 170 300  35]

Primeros 3 registros normalizados: 
[[0.86885246 0.83333333 0.85714286 0.78571429]
 [0.08196721 0.         0.07142857 0.07142857]
 [0.75409836 0.58333333 0.57142857 0.57142857]]


## **Cuando normalizar los datos**
La normalización se utiliza para que no se de mas peso a ciertos datos por ejemplo:

El registro: 6

Tiene los siguientes datos: 45 130 210 26

Si no normalizamos esta información el perceptron le dara mucha mas importancia al valor de colesterol 210 por encima de la edad de 45, cuando no necesariamente podria ser asi.

Al normalizar esta infomación todos los valores estaran en un rango entre 0 a 1 y evitaremos este posible sesgo en la información y todos los datos tendran la misma relevancia para poder realizar un entrenamiento optimo.

In [55]:
#Dividir en datos de entrenamiento y datos de testeo
x_entrenamiento = datos_normalizados[:30,:]
y_entrenamiento = etiquetas[:30]
print(f"Cantidad datos entrenamiento: {len(x_entrenamiento)}, Cantidad datos testeo: {len(y_entrenamiento)}")
x_testeo = datos_normalizados[30:,:]
y_testeo = etiquetas[30:]
print(f"Cantidad etiquetas entrenamiento: {len(x_testeo)}, Cantidad etiquetas testeo: {len(y_testeo)}")

#print("datos entrenamiento")
#print(x_entrenamiento)
print(x_testeo)
#print("datos testeo")
#print(y_entrenamiento)
print(y_testeo)


Cantidad datos entrenamiento: 30, Cantidad datos testeo: 30
Cantidad etiquetas entrenamiento: 10, Cantidad etiquetas testeo: 10
[[0.19672131 0.2        0.25       0.21428571]
 [0.7704918  0.6        0.58571429 0.64285714]
 [0.44262295 0.41666667 0.42857143 0.42857143]
 [0.85245902 0.75       0.75       0.78571429]
 [0.09836066 0.1        0.14285714 0.07142857]
 [0.62295082 0.58333333 0.64285714 0.57142857]
 [0.24590164 0.23333333 0.22857143 0.28571429]
 [0.73770492 0.66666667 0.62857143 0.71428571]
 [0.14754098 0.15       0.12857143 0.14285714]
 [0.8852459  0.86666667 0.89285714 0.85714286]]
[0 1 0 1 0 1 0 1 0 1]


## **Precisión**
Los datos se dividen en entrenamiento y testeo para poder realizar el calculo de la presición.

Si de 10 pasientes el perceptrón identifica correctamente a 9 de ellos, podemos decir que tiene una precisión del 90%

In [61]:
#Iniciamos los pesos y el bias
pesos = np.random.uniform(-1,1,4)
bias = np.random.uniform(-1,1)
tasa_aprendizaje = 0.01
epocas = 200
print(pesos)
print(bias)

[ 0.11471155  0.82522537  0.52207717 -0.51770346]
0.8712180913601388


In [62]:
#Entrenamiento
for epoca in range(epocas):
  error_total = 0
  for i in range (len(x_entrenamiento)):
    #Prediccion (Suma ponderada + bias)
    #print(f"datos entrenamiento: {x_entrenamiento[i]}, bias: {bias}")
    suma_z = np.dot(x_entrenamiento[i],pesos) + bias
    prediccion = 1 if suma_z > 0 else 0

    #Calculo error
    error = y_entrenamiento[i] - prediccion
    error_total += abs(error)

    #Ajuste de pesos y bias
    pesos += tasa_aprendizaje * error * x_entrenamiento[i]
    bias += tasa_aprendizaje * error
  print(f"Epoca: {epoca+1}, Cantidad errores = {error_total} ")
  if (error_total == 0):
    print("Perceptron entrenado")
    break

Epoca: 1, Cantidad errores = 15 
Epoca: 2, Cantidad errores = 15 
Epoca: 3, Cantidad errores = 15 
Epoca: 4, Cantidad errores = 15 
Epoca: 5, Cantidad errores = 15 
Epoca: 6, Cantidad errores = 15 
Epoca: 7, Cantidad errores = 9 
Epoca: 8, Cantidad errores = 7 
Epoca: 9, Cantidad errores = 7 
Epoca: 10, Cantidad errores = 7 
Epoca: 11, Cantidad errores = 6 
Epoca: 12, Cantidad errores = 5 
Epoca: 13, Cantidad errores = 4 
Epoca: 14, Cantidad errores = 5 
Epoca: 15, Cantidad errores = 5 
Epoca: 16, Cantidad errores = 4 
Epoca: 17, Cantidad errores = 2 
Epoca: 18, Cantidad errores = 3 
Epoca: 19, Cantidad errores = 4 
Epoca: 20, Cantidad errores = 2 
Epoca: 21, Cantidad errores = 3 
Epoca: 22, Cantidad errores = 2 
Epoca: 23, Cantidad errores = 2 
Epoca: 24, Cantidad errores = 2 
Epoca: 25, Cantidad errores = 2 
Epoca: 26, Cantidad errores = 2 
Epoca: 27, Cantidad errores = 3 
Epoca: 28, Cantidad errores = 2 
Epoca: 29, Cantidad errores = 2 
Epoca: 30, Cantidad errores = 2 
Epoca: 31, Ca

In [63]:
#Funcion perceptron
def calcular_prediccion (fila_dato, pesos, bias):
  z = np.dot(fila_dato, pesos) + bias
  return 1 if z > 0 else 0

In [64]:
#Testeo Precicion Perceptron
def test_precision(data, result_real, pesos, bias):
  aciertos = 0
  total = len(data)

  print("\n--- Resultados del Testeo ---")
  for i in range(total):
    res = calcular_prediccion(data[i], pesos, bias)

    if res == result_real[i]:
      aciertos += 1

    print(f"Paciente {i+1}: Predicción: {res}, Real: {result_real[i]}")

  precision = (aciertos / total) * 100
  print(f"\nTotal aciertos: {aciertos}/{total}")
  print(f"Precisión: {precision}%")


In [65]:
test_precision(x_testeo, y_testeo, pesos, bias)


--- Resultados del Testeo ---
Paciente 1: Predicción: 0, Real: 0
Paciente 2: Predicción: 1, Real: 1
Paciente 3: Predicción: 1, Real: 0
Paciente 4: Predicción: 1, Real: 1
Paciente 5: Predicción: 0, Real: 0
Paciente 6: Predicción: 1, Real: 1
Paciente 7: Predicción: 0, Real: 0
Paciente 8: Predicción: 1, Real: 1
Paciente 9: Predicción: 0, Real: 0
Paciente 10: Predicción: 1, Real: 1

Total aciertos: 9/10
Precisión: 90.0%
